language: python
dist: xenial
python:
  - "3.7"

branches:
  only:
    - "master"

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - poetry config virtualenvs.in-project true

jobs:
  include:
    - name: unittest
      script: poetry run pytest pii_recognition