language: python
dist: xenial
python:
  - "3.7"

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - poetry config settings.virtualenvs.in-project true

jobs:
  include:
    - name: unittest
      script: poetry run pytest pii_recognition